import type { Metadata } from "next";
import Link from "next/link";
import "./guide.css";

export const metadata: Metadata = {
  title: "How to Use This Website | Visual Library",
  description: "A plain-English introduction to the courses, case studies, mission labs, search, and reading tools in the Visual Library.",
};

export default function HowToUse() {
  return <div className="welcome-guide">
    <header className="welcome-top"><Link href="/">← Back to the learning library</Link></header>
    <main id="guide-content">
      <section className="welcome-hero"><p className="welcome-eyebrow">NEW HERE? START HERE.</p><h1>How to use this website</h1><p className="welcome-lead">Learn a concept. See it used in a project. Then practise making decisions yourself.</p><p>You do not need to read everything in order. This is a learning library—not a course with compulsory steps, scores, or a progress bar. Choose a topic that interests you and explore at your own pace.</p><div className="welcome-note"><strong>The simplest way to begin:</strong> open a visual course, read one lesson and its diagram, then try a related case study or mission. You can always return here using the button at the top right.</div></section>

      <nav className="welcome-toc" aria-label="In this guide"><strong>In this guide</strong><div>{[["map", "Find your way around"], ["first-visit", "Your first visit"], ["reading", "Read comfortably"], ["search", "Find a topic"], ["missions", "Try a mission"], ["questions", "Common questions"]].map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</div></nav>

      <section id="map" className="welcome-card"><h2>1. Find your way around</h2><p>On the main library page, the left-hand menu has three shelves. Choose a shelf, open a collection, expand a section, and select an article. Long menu titles wrap so you can read the whole name.</p><div className="welcome-grid">
        <article><p className="welcome-eyebrow">LEARN THE IDEAS</p><h3>Courses</h3><p>The ten visual courses explain concepts through diagrams and detailed lessons. Start here when you want to understand what a technology does and how its parts fit together.</p><Link href="/#shelf=course">Browse the courses →</Link></article>
        <article><p className="welcome-eyebrow">SEE A WHOLE PROJECT</p><h3>Case Studies</h3><p>Acme, Hospital, and FilePilot connect the concepts to project designs, architectures, safety rules, and build guides. Start here when you want to see how several technologies work together.</p><Link href="/#shelf=case-study">Browse the case studies →</Link></article>
        <article><p className="welcome-eyebrow">BUILD YOUR SKILLS</p><h3>Library Guides</h3><p>Find the software-engineering workshops, including CI/CD, debugging, testing, APIs, Git, and more. There are also guides to the document collection and publishing workflow.</p><Link href="/#course=library-guides&chapter=18">Open the workshop introduction →</Link></article>
      </div><div className="welcome-note"><strong>On a phone:</strong> tap the ☰ menu button in the library header to open the sidebar. Select an article to return to reading. Mission pages use their own grouped mission menu instead.</div></section>

      <section id="first-visit" className="welcome-card"><h2>2. A simple first visit</h2><ol className="welcome-path" aria-label="Suggested learning sequence"><li><span>01</span><h3>Read one lesson</h3><p>Choose a course topic. Read “At a glance,” inspect the diagram, and work through the explanation.</p></li><li><span>02</span><h3>See the project</h3><p>Open a case study’s introduction. Follow the same idea through a practical workflow.</p></li><li><span>03</span><h3>Try a decision</h3><p>Open a mission lab, inspect its evidence, and choose an action. Read why the outcome happened.</p></li></ol><p>This is a suggested route, not a requirement. If you prefer learning by doing, start with <Link href="/labs/filepilot#mission=1">FilePilot’s first mission</Link>: organize fictional files, approve the proposed moves, and undo the result.</p></section>

      <section id="reading" className="welcome-card"><h2>3. Make reading comfortable</h2><dl className="welcome-features"><div><dt>Text size: 22, 24, or 28</dt><dd>Use the controls near the top of a library article to choose a comfortable body-text size. The site remembers that preference in this browser when browser storage is available. These controls apply to library articles, not every standalone lab page.</dd></div><div><dt>On this page</dt><dd>Open the article’s contents list and select a heading to jump to that section. It is useful when you want to revisit one idea without scrolling through the whole lesson.</dd></div><div><dt>Enlarge diagram</dt><dd>Use the button beside a diagram to inspect it at a larger size. Close the enlarged view with its Close button or the Escape key.</dd></div><div><dt>Previous and Next</dt><dd>Use the buttons at the bottom of an article to move through its collection. You can also jump directly to another article in the sidebar.</dd></div><div><dt>Bookmarks, not progress tracking</dt><dd>Bookmark the current page in your browser if you want to return to a lesson or mission. There are no reading scores, completion checkmarks, or saved course-progress records.</dd></div></dl></section>

      <section id="search" className="welcome-card"><h2>4. Find a topic quickly</h2><p>Use <strong>“Search the whole library”</strong> in the sidebar. Try a term such as “RAG,” “authorization,” or “debugging.” Select a result to open the article. Matching text can be highlighted, with Previous and Next controls for moving between matches.</p><p>Clear the search box to return to ordinary browsing. Search covers published course articles, case-study documents, and library guides. The interactive mission scenarios are not part of that article search—use the grouped mission selectors on the lab pages to explore them.</p><div className="welcome-note"><strong>A useful habit:</strong> begin with one specific term. If you find a detailed article that assumes background knowledge, use its collection’s introduction to get your bearings.</div></section>

      <section id="missions" className="welcome-card"><h2>5. Try the mission labs</h2><p>The three lab links in the library sidebar each open a collection of 30 exercises. Their menus are grouped into sets of ten. Expand a group, then choose a mission.</p><div className="welcome-grid">
        <article><h3>FilePilot</h3><p>Practise file organization, searching, duplicate detection, approvals, safe sharing, and recovery.</p><Link href="/labs/filepilot">Open FilePilot labs →</Link></article>
        <article><h3>Acme</h3><p>Investigate trustworthy answers, agent teamwork, failed tool calls, budgets, and release decisions.</p><Link href="/labs/acme">Open Acme labs →</Link></article>
        <article><h3>Hospital / HarborCare</h3><p>Explore identity, scoped access, permitted sharing, privacy failures, and recovery using synthetic records.</p><Link href="/labs/hospital">Open Hospital labs →</Link></article>
      </div><h3>How an investigation works</h3><ol className="welcome-steps"><li><strong>Read the task and its limits.</strong> Understand what the requester is asking for and what the scenario permits.</li><li><strong>Inspect the evidence.</strong> When evidence cards are present, open all of them before comparing strategies. Some earlier guided missions present the evidence directly instead.</li><li><strong>Choose a response.</strong> Try a questionable shortcut if you want to learn why it gets blocked. The exercise gives you a way back to the decision.</li><li><strong>Review before approval.</strong> In investigation missions, inspect the exact proposal and its scope before approving that strategy.</li><li><strong>Read the result and debrief.</strong> Compare the trade-offs. The decision trail records your choices for this session; it is an educational record, not a production audit log.</li><li><strong>Restart to experiment.</strong> Try another strategy and explain why you would choose it. Switching missions or refreshing resets the exercise; bookmarking a mission does not save its current state.</li></ol><div className="welcome-note"><strong>These are simulations.</strong> They use fictional data and predefined outcomes. They do not connect to your files, run live agents, or contact agencies. Hospital exercises use fictional policies and are not clinical or legal advice or proof of compliance. FilePilot’s first lab lets you manipulate an in-memory fictional folder; it still cannot change your actual files.</div></section>

      <section className="welcome-card"><h2>6. Understand the key terms</h2><dl className="welcome-features"><div><dt>MCP — connecting an assistant to tools</dt><dd>Model Context Protocol provides a standard interface for tools and resources. A tool connection does not automatically grant permission to use every operation or access every record.</dd></div><div><dt>RAG — finding evidence before answering</dt><dd>Retrieval-augmented generation brings relevant source material into an answer workflow. You still need to check whether the sources are permitted, current, and actually support the answer.</dd></div><div><dt>A2A — agents coordinating work</dt><dd>Agent-to-agent communication lets specialist agents exchange tasks and results. They still need clear responsibilities, validated inputs, and appropriate authority.</dd></div><div><dt>CI/CD — checking and releasing changes</dt><dd>Continuous integration and delivery/deployment workflows help test, review, and release software changes. The workshops explain why a successful build is not the same as a complete or safe feature.</dd></div></dl></section>

      <section id="questions" className="welcome-card"><h2>Common questions</h2><details><summary>Do I need an account?</summary><p>No sign-in is required to browse the library or try these mission labs. Some hands-on workshops may ask you to use your own development tools or external accounts; their instructions explain the setup.</p></details><details><summary>Do I need to finish a course before trying a lab?</summary><p>No. You can start with a mission and return to the courses when you want a deeper explanation. Use the case-study link on a lab page to connect the exercise with its project design.</p></details><details><summary>Why did a mission reset?</summary><p>Mission state lives in the current browser page. Refreshing, leaving the page, or switching missions can reset it. There is no saved progress account. A bookmark returns you to the mission, not to a saved sequence of decisions.</p></details><details><summary>Does completing a lab mean I built the real system?</summary><p>No. A lab helps you practise the reasoning. The case-study build guides explain implementation work. Real systems require additional code, tests, infrastructure, authorization, and operational review.</p></details><details><summary>Can I use the site with a keyboard?</summary><p>Use Tab to move between links and controls, Enter to follow a link, and Enter or Space to activate a button. The library’s “Skip to content” link appears when focused. Escape closes the enlarged-diagram dialog.</p></details></section>
      <section className="welcome-finish"><h2>You’re ready to explore.</h2><p>Pick one useful question, read one explanation, or try one mission. There is no need to tackle the whole library at once.</p><div><Link href="/" className="welcome-primary">Open the learning library →</Link><Link href="/labs/filepilot#mission=1">Try your first mission →</Link></div></section>
    </main><footer>Visual Library · Understand it. Inspect it. Practise it.</footer>
  </div>;
}
