import type { Mission } from "./filepilot-missions";

type Strategy = { label: string; review: string; plan: string[]; result: string[]; tradeoff: string };
type Investigation = {
  id: number; title: string; topic: string; brief: string;
  clues: { title: string; text: string }[];
  shortcut: string; rejection: string; rejectedEvidence: string[];
  strategies: [Strategy, Strategy]; lesson: string;
};

function investigation(config: Investigation): Mission {
  const [a, b] = config.strategies;
  const choice = (label: string, next: string) => ({ label, next });
  return {
    id: config.id, title: config.title, topic: config.topic, brief: config.brief,
    boundary: "This investigation uses fixed fictional evidence and predefined outcomes. It does not inspect files, run tools, or contact external services.",
    clues: config.clues.map((c, i) => ({ ...c, id: `clue-${i + 1}` })),
    comparison: config.strategies.map(s => ({ title: s.label, explanation: s.tradeoff })),
    steps: {
      start: { title: "Inspect the case before choosing", explanation: "Open each evidence card. Compare what the task asks for with the observed state; do not assume a filename or a success message tells the whole story.", evidence: [config.brief, "No operation has been authorized or executed."], actions: [choice("Compare the available strategies", "decision")] },
      decision: { title: "Choose your response", explanation: "There are two defensible strategies here, with different costs. A third option skips an important check. Pick a response and inspect its consequences before approving anything.", evidence: config.clues.map(c => `${c.title}: ${c.text}`), actions: [choice(a.label, "review-a"), choice(config.shortcut, "blocked"), choice(b.label, "review-b")] },
      blocked: { title: "That shortcut does not satisfy the policy", explanation: config.rejection, evidence: config.rejectedEvidence, blocked: true, actions: [choice("Reconsider using the evidence", "decision")] },
      "review-a": { title: "Review strategy A", explanation: a.review, evidence: a.plan, actions: [choice("Choose a different strategy", "decision"), choice("Approve this exact strategy", "result-a")] },
      "review-b": { title: "Review strategy B", explanation: b.review, evidence: b.plan, actions: [choice("Choose a different strategy", "decision"), choice("Approve this exact strategy", "result-b")] },
      "result-a": { title: "Inspect the result of strategy A", explanation: a.tradeoff, evidence: a.result, actions: [choice("Review the lesson and compare alternatives", "done")] },
      "result-b": { title: "Inspect the result of strategy B", explanation: b.tradeoff, evidence: b.result, actions: [choice("Review the lesson and compare alternatives", "done")] },
      done: { title: "Investigation debrief", explanation: config.lesson, evidence: ["Your decision trail records the strategy you actually selected and its simulated result.", "The alternatives below explain what a different choice would trade off; they were not both executed.", "Explain which assumption failed and what you would verify in a real implementation."], complete: true, actions: [] }
    }
  };
}

export const investigations: Mission[] = [
  investigation({ id: 11, title: "The Folder That Leads Somewhere Else", topic: "Path boundaries · symbolic links", brief: "Inspect Demo/Inbox without following a link into an unauthorized private folder.", clues: [
    { title: "Scope", text: "The grant permits reading Demo/Inbox only. Demo/Private is not authorized." },
    { title: "Directory entry", text: "Demo/Inbox/accounts is a symbolic link, not an ordinary subfolder." },
    { title: "Resolved target", text: "The link resolves to Demo/Private/accounts. No target contents have been read." }
  ], shortcut: "Read it because the displayed path starts with Inbox", rejection: "A lexical prefix is not sufficient evidence of containment. The resolved target is outside the grant, so the scenario rejects the read.", rejectedEvidence: ["Target outside allowed root", "Private bytes returned: 0"], strategies: [
    { label: "Skip linked entries for this scan", review: "Use a no-follow scan and report the skipped entry. Do not imply that the scan covered everything.", plan: ["Read ordinary permitted files only", "Skip accounts link", "Report incomplete coverage"], result: ["Permitted ordinary files listed", "accounts: skipped", "No private reads"], tradeoff: "Simpler policy and predictable scope, but legitimate linked content is omitted." },
    { label: "Request a separately scoped review of the target", review: "Pause this item and ask the owner to review a new scope. A request is not an automatic grant.", plan: ["Keep current grant unchanged", "Queue scope review for Demo/Private/accounts", "Do not follow link while waiting"], result: ["Review request recorded", "Linked content remains unread", "Scan result marked partial"], tradeoff: "Can support legitimate linked resources later, but adds review time. The target is still inaccessible now." }
  ], lesson: "Scope must follow the actual resource, not just its displayed name. Real implementations also need race-resistant handling of links and platform-specific path behavior." }),
  investigation({ id: 12, title: "Same Name, Different Computer", topic: "Portability · name collisions", brief: "Copy a Linux folder to a case-insensitive destination without collapsing distinct documents.", clues: [
    { title: "Source names", text: "Report.txt contains ‘draft’; report.txt contains ‘approved’. They are distinct source files." },
    { title: "Destination behavior", text: "This particular destination treats Report.txt and report.txt as the same name." },
    { title: "Preservation requirement", text: "Both contents must survive, and downstream consumers need a recorded name mapping." }
  ], shortcut: "Copy both names unchanged and accept the last one", rejection: "On this destination the second name collides. A last-write-wins policy would discard a distinct version.", rejectedEvidence: ["Collision detected before copy", "Source files unchanged"], strategies: [
    { label: "Assign distinct destination names", review: "Review descriptive names and record the mapping before copying.", plan: ["Report.txt → report-draft.txt", "report.txt → report-approved.txt", "Preserve both sources"], result: ["Two destination files with distinct names", "Both contents retained", "Name mapping recorded"], tradeoff: "Keeps files easy to browse but requires consumers to use the new names." },
    { label: "Place the versions in separate directories", review: "Keep basenames but separate them structurally.", plan: ["Report.txt → draft/Report.txt", "report.txt → approved/report.txt", "Verify both destination paths"], result: ["Two files in separate directories", "Both contents retained", "Directory mapping recorded"], tradeoff: "Preserves original basenames but changes folder structure and relative references." }
  ], lesson: "Do not assume all Windows or Linux volumes behave identically. Probe the actual target’s name rules and check collisions before moving data." }),
  investigation({ id: 13, title: "The File That Is Still Being Written", topic: "Readiness · producer coordination", brief: "Avoid filing an invoice download while its producer is still writing it.", clues: [
    { title: "Observed size", text: "invoice.pdf.part grew from 12 KB to 47 KB between observations." },
    { title: "Producer contract", text: "This downloader publishes invoice.pdf only after closing the completed temporary file." },
    { title: "Deadline", text: "The organizer may defer an item; an immediate result is not required." }
  ], shortcut: "Treat a short pause in growth as proof of completion", rejection: "A paused writer may resume. A stable size over a short interval does not satisfy the producer’s completion contract.", rejectedEvidence: ["Final publication event absent", "File left untouched"], strategies: [
    { label: "Wait for the producer’s final publication", review: "Observe a bounded wait for the documented ready signal, then recheck the file.", plan: ["Wait for final invoice.pdf publication", "Verify expected final entry", "Only then queue organization"], result: ["Simulated producer publishes final file", "Organizer receives ready item", "Temporary file never moved"], tradeoff: "Automates the handoff when a reliable producer contract exists, but still needs timeouts and failure handling." },
    { label: "Defer this item and continue other work", review: "Record why it was skipped and require a later readiness check.", plan: ["Skip the .part file", "Record pending readiness", "Continue independent ready items"], result: ["Invoice remains pending", "Other ready files processed", "No incomplete invoice filed"], tradeoff: "Keeps the batch moving but requires a follow-up; the skipped item is not falsely marked finished." }
  ], lesson: "Readiness should come from a defined handoff, not a guess based on timing. A file’s existence does not prove that its contents are complete." }),
  investigation({ id: 14, title: "The Locked Document", topic: "Resource contention · bounded retry", brief: "Handle a move denied because another application currently holds the document open.", clues: [
    { title: "Error", text: "The simulated filesystem reports a sharing violation for agenda.docx." },
    { title: "Owner", text: "An editor is saving changes; terminating it could lose work." },
    { title: "Batch policy", text: "Independent files may continue. At most three delayed retries are allowed for this item." }
  ], shortcut: "Force-close the editor to free the file", rejection: "The organizer has no authority to terminate the editor or discard another user’s work.", rejectedEvidence: ["No process terminated", "agenda.docx remains in place"], strategies: [
    { label: "Use bounded retries with revalidation", review: "Retry at most three times, rechecking the source and destination each time. A timeout must become a visible pending item.", plan: ["Maximum three retries", "Check identity and destination again", "Stop on exhaustion"], result: ["Fixture editor releases the file on retry 2", "Source and destination revalidated", "Move completes without terminating editor"], tradeoff: "Handles short-lived locks automatically but adds delay and cannot guarantee eventual success." },
    { label: "Skip the locked item and notify its owner", review: "Leave the file where it is and report the incomplete batch item.", plan: ["Do not retry now", "Continue independent items", "Notify owner of pending move"], result: ["agenda.docx unchanged", "Pending item reported", "Other batch work can continue"], tradeoff: "Avoids waiting but requires later coordination. A partial batch must remain visibly partial." }
  ], lesson: "Different errors need different responses. Retry a transient lock within a limit; do not hide it, loop forever, or terminate an unrelated application." }),
  investigation({ id: 15, title: "The Disk Is Almost Full", topic: "Capacity · partial copies", brief: "Copy an 800 MB media pack when the target has only 300 MB available.", clues: [
    { title: "Capacity", text: "Source size: 800 MB. Target free space: 300 MB before overhead and concurrent activity." },
    { title: "Safety contract", text: "Sources cannot be deleted until a complete verified copy exists." },
    { title: "Alternative", text: "An approved staging volume has 2 GB free; its access permissions match the project." }
  ], shortcut: "Start copying and delete sources as each chunk finishes", rejection: "A chunk is not a verified file. Removing source data during an incomplete copy threatens recoverability.", rejectedEvidence: ["Capacity preflight failed", "No source deleted", "No partial output published as complete"], strategies: [
    { label: "Pause until the owner supplies enough space", review: "Ask for space without choosing files to delete on the owner’s behalf.", plan: ["Leave source intact", "Do not start target copy", "Request adequate capacity plus headroom"], result: ["Copy remains pending", "Source intact", "Owner receives capacity shortfall"], tradeoff: "Uses the intended target and minimizes complexity, but delays delivery." },
    { label: "Stage on the approved alternate volume", review: "Copy to a temporary name, verify it, then publish it on the staging volume. Keep the source.", plan: ["Recheck staging permissions and capacity", "Copy and verify all bytes", "Record alternate location; retain source"], result: ["Verified staging copy available", "Intended target still pending", "Original preserved"], tradeoff: "Makes a usable copy sooner but creates another location to manage. A capacity check is not a reservation against other writers." }
  ], lesson: "Plan for insufficient space and cleanup of partial outputs. Never confuse a successful start with a complete, verified copy." }),
  investigation({ id: 16, title: "Undo Is No Longer Safe", topic: "Recovery conflicts · human edits", brief: "Reverse yesterday’s organization without losing changes someone made afterward.", clues: [
    { title: "Operation record", text: "Yesterday: Inbox/notes.txt v1 moved to Documents/notes.txt." },
    { title: "Current document", text: "Documents/notes.txt is now v2 with a colleague’s added paragraph." },
    { title: "Original location", text: "Inbox/notes.txt now exists again with different content, created by another process." }
  ], shortcut: "Restore yesterday’s snapshot over both current paths", rejection: "That would erase work created after the original operation. Undo is a new state-changing operation and must be checked against current reality.", rejectedEvidence: ["Destination occupied", "Moved file has changed", "Automatic reversal blocked"], strategies: [
    { label: "Preserve both versions in a recovery copy", review: "Copy the current v2 document to a new conflict-free recovery location. Do not replace either existing file.", plan: ["Create Recovery/notes-v2.txt after collision check", "Keep Documents/notes.txt v2", "Keep current Inbox/notes.txt"], result: ["Current work preserved", "Recovery copy available for comparison", "Original move not fully reversed"], tradeoff: "Offers a useful recovery artifact immediately, but creates an extra copy and does not restore the old layout." },
    { label: "Freeze the reversal and request an owner decision", review: "Present both paths and version evidence without making further changes.", plan: ["No writes", "Record conflict details", "Ask owner which version and location to retain"], result: ["Both current files untouched", "Undo remains pending", "Owner review requested"], tradeoff: "Minimizes further mutation but delays recovery. The system must not report that undo succeeded." }
  ], lesson: "Recoverability is conditional on later state. A historical snapshot is not blanket permission to overwrite everything that changed afterward." }),
  investigation({ id: 17, title: "The Archive Surprise", topic: "Archive extraction · path traversal", brief: "Inspect an archive before allowing any entries to reach the destination folder.", clues: [
    { title: "Archive listing", text: "Entries: readme.txt, images/logo.png, ../../Private/config.txt." },
    { title: "Allowed destination", text: "Extraction is permitted only inside Demo/Extracted." },
    { title: "Preflight", text: "Nothing has been extracted. Entry sizes and link metadata can be inspected first." }
  ], shortcut: "Extract everything and inspect the result afterward", rejection: "Inspection after extraction is too late if an entry escapes the destination. The traversal entry fails preflight.", rejectedEvidence: ["Rejected entry: ../../Private/config.txt", "Files extracted: 0"], strategies: [
    { label: "Reject the entire archive", review: "Preserve the unopened archive and request a corrected package.", plan: ["Do not extract any entry", "Record invalid path", "Ask sender for a clean archive"], result: ["No extracted files", "Original archive preserved", "Correction requested"], tradeoff: "A simple all-or-nothing boundary, but delays access to harmless entries too." },
    { label: "Approve only validated ordinary entries", review: "Select the two ordinary entries after path, type, link, collision, and size checks in the fixture. Exclude the traversal entry.", plan: ["Allow readme.txt and images/logo.png", "Exclude traversal entry", "Apply extraction size and count limits"], result: ["Two permitted entries extracted in simulation", "Traversal entry excluded", "Partial extraction explicitly reported"], tradeoff: "Recovers useful content but requires a carefully implemented extractor; filename filtering alone is not sufficient." }
  ], lesson: "Validate the whole extraction plan before writing. Real archive handling also needs defenses for links, decompression limits, collisions, and races." }),
  investigation({ id: 18, title: "The Disguised File", topic: "File identity · safe inspection", brief: "Decide how to handle an attachment called invoice.pdf when its format evidence disagrees.", clues: [
    { title: "Filename", text: "The attachment is named invoice.pdf." },
    { title: "Format inspection", text: "The fixture’s signature check indicates an executable, not a PDF document." },
    { title: "Task", text: "The user requested an invoice summary, not permission to execute an application." }
  ], shortcut: "Open it normally because the extension is .pdf", rejection: "The name conflicts with the format evidence. Opening an unexpected executable is outside the summarization task.", rejectedEvidence: ["Normal open blocked", "File never executed"], strategies: [
    { label: "Quarantine the attachment for review", review: "Use a restricted holding location, preserve evidence, and avoid execution.", plan: ["Record name and inspection result", "Quarantine without opening", "Notify reviewer"], result: ["Attachment isolated in simulation", "Invoice summary withheld", "Review requested"], tradeoff: "Keeps the suspicious item available for investigation but requires controlled handling and retention." },
    { label: "Reject it and request a genuine invoice", review: "Do not claim to have parsed an invoice. Ask the sender for the expected document format.", plan: ["No execution or parsing", "Reject this item from the workflow", "Request a corrected invoice"], result: ["Summary task pending", "Replacement requested", "Original not processed"], tradeoff: "Keeps the business workflow simple but does not investigate the suspicious file further." }
  ], lesson: "Extensions and declared content types are hints, not proof of safety. Even a valid PDF can be hostile; safe parsing remains a separate concern." }),
  investigation({ id: 19, title: "Secrets Hidden in Plain Sight", topic: "Redaction · exposure response", brief: "Prepare a shareable copy of a project note containing a fictional access token.", clues: [
    { title: "Document label", text: "The note is labelled public, but labels can be wrong." },
    { title: "Content", text: "One line says API_TOKEN=DEMO-NOT-A-REAL-SECRET. This is synthetic teaching data." },
    { title: "Sharing history", text: "The fixture says an earlier version may already have been shared externally." }
  ], shortcut: "Share the original because its label says public", rejection: "The content contradicts the label. A classification label cannot override known sensitive content.", rejectedEvidence: ["Original excluded from sharing", "No external transfer"], strategies: [
    { label: "Prepare and review a redacted derivative", review: "Remove the token line from a separate sharing copy, review the whole derivative, and separately flag possible prior exposure.", plan: ["Preserve restricted original", "Review redacted copy and metadata", "Notify credential owner about possible prior exposure"], result: ["Reviewed derivative ready in simulation", "Original retained privately", "Exposure follow-up remains open"], tradeoff: "Can unblock document sharing, but redaction does not revoke a previously exposed credential or erase old copies." },
    { label: "Hold sharing pending credential-owner review", review: "Stop the handover and request exposure assessment. No actual token is revoked in this lab.", plan: ["No sharing copy released", "Notify owner", "Require an approved clean document"], result: ["Handover pending", "Owner review requested", "No claim that prior exposure is resolved"], tradeoff: "More conservative and slower; avoids releasing a derivative before the owner reviews the incident." }
  ], lesson: "A clean sharing copy and an exposure response solve different problems. Removing a string from a document is not credential rotation." }),
  investigation({ id: 20, title: "The Photograph That Reveals Too Much", topic: "Metadata · derivative verification", brief: "Share a fictional site photograph without revealing its embedded location.", clues: [
    { title: "Visible image", text: "The photo shows an office entrance with a readable street sign." },
    { title: "Metadata", text: "The fictional metadata contains GPS coordinates and a photographer name." },
    { title: "Retention", text: "The original must remain intact in the private archive." }
  ], shortcut: "Strip GPS and assume the image is anonymous", rejection: "Location can remain visible in the pixels. Removing one metadata field does not establish anonymity.", rejectedEvidence: ["Street sign still readable", "Sharing not approved"], strategies: [
    { label: "Create a reviewed privacy-safe derivative", review: "Remove unnecessary metadata and obscure the visible sign in a copy, then inspect both metadata and pixels.", plan: ["Original unchanged", "Review derivative metadata", "Review visible location clues"], result: ["Fixture derivative has no GPS or name metadata", "Street sign obscured", "Derivative approved for this fictional sharing scope"], tradeoff: "Retains useful visual context, but privacy review is contextual and cannot guarantee that no location clues remain." },
    { label: "Use an approved generic illustration instead", review: "Replace the photograph in the sharing pack with a pre-approved non-location-specific image.", plan: ["Keep original private", "Select approved generic illustration", "Label it as illustrative"], result: ["No site photo shared", "Generic image included", "No claim that the illustration depicts the actual site"], tradeoff: "Reduces location exposure but loses site-specific detail and must not misrepresent the illustration as evidence." }
  ], lesson: "Privacy can live in metadata and in visible content. Preserve originals and verify the actual derivative that will be shared." }),
  investigation({ id: 21, title: "The Search Index Remembers Too Much", topic: "RAG permissions · revocation", brief: "Prevent a revoked user from receiving a document passage that remains in a stale search index.", clues: [
    { title: "Live access rule", text: "The user’s access to forecast.txt was revoked at 10:00." },
    { title: "Index snapshot", text: "The search index still has a 09:50 passage and an old allow label." },
    { title: "Output boundary", text: "The candidate has not reached the answer generator or user. Live authorization can still reject it." }
  ], shortcut: "Trust the index’s older permission label", rejection: "A cached allow decision cannot override a live revocation. The passage must be excluded before it reaches the answer context.", rejectedEvidence: ["Restricted candidate withheld", "Snippet and answer leakage: none in this fixture"], strategies: [
    { label: "Reauthorize candidates and invalidate stale entries", review: "Apply current access rules to each candidate before snippets or answer generation; queue index and cache invalidation.", plan: ["Reject forecast.txt for this user", "Continue only with currently authorized candidates", "Queue invalidation and verify it later"], result: ["Restricted passage absent from answer context", "Other permitted results available", "Invalidation follow-up recorded"], tradeoff: "Maintains partial search availability but depends on reliable live authorization and consistent cache treatment." },
    { label: "Pause the affected search collection", review: "Fail closed for this collection until permissions, index entries, and answer caches are reconciled.", plan: ["No results from affected collection", "Reconcile revocations", "Reopen only after verification"], result: ["Search temporarily unavailable for this collection", "No stale passages returned", "Reconciliation required before reopening"], tradeoff: "Stronger containment during uncertainty, at the cost of availability for otherwise permitted queries." }
  ], lesson: "RAG authorization must protect snippets, model context, citations, and caches—not just document downloads. Revocation has to propagate through the whole retrieval path." }),
  investigation({ id: 22, title: "Two Documents Disagree", topic: "Source authority · conflicting evidence", brief: "Answer an onboarding question when two documents prescribe different steps.", clues: [
    { title: "Document A", text: "onboarding-v2.txt says to email forms. It was superseded last month." },
    { title: "Document B", text: "onboarding-v3.txt says to use the secure portal. The policy register marks it current for this team." },
    { title: "Question scope", text: "The learner belongs to this team; no regional exception is documented in the fixture." }
  ], shortcut: "Blend the instructions into one combined answer", rejection: "Combining incompatible versions can invent a procedure that no authoritative source supports.", rejectedEvidence: ["Mixed-version answer withheld", "Conflict preserved rather than hidden"], strategies: [
    { label: "Answer from the registered current version", review: "Use B for this scoped question and explicitly mention that A is superseded.", plan: ["Answer: use secure portal", "Cite current policy B", "Note superseded source A"], result: ["Current procedure reported", "Conflict explained", "No invented hybrid steps"], tradeoff: "Gives a timely answer when authority and scope are established; relies on the policy register being trustworthy." },
    { label: "Request policy-owner confirmation", review: "Present the conflict and hold a definitive answer until the owner confirms the applicable instruction.", plan: ["Show both version statuses", "Ask owner to confirm team scope", "Do not recommend emailing forms"], result: ["Definitive answer pending", "Owner review requested", "No mixed procedure delivered"], tradeoff: "Adds caution for consequential uncertainty, but delays an answer the current register already supports." }
  ], lesson: "Recency and similarity are not the same as authority. Resolve scope and version status, or disclose uncertainty rather than blending contradictions." }),
  investigation({ id: 23, title: "The Scanned Invoice", topic: "OCR uncertainty · validation", brief: "Avoid filing an invoice under the wrong amount after uncertain text recognition.", clues: [
    { title: "Recognized amount", text: "OCR suggests 8,100 with low confidence on the first digit." },
    { title: "Arithmetic", text: "Visible line items total 3,000 plus 100 tax: 3,100." },
    { title: "Workflow", text: "The proposed filename embeds the amount, so a recognition mistake would propagate into filing." }
  ], shortcut: "Accept the OCR amount as the filename", rejection: "The low-confidence amount conflicts with the arithmetic. A successful OCR response is not proof of a correct field.", rejectedEvidence: ["Amount-based rename blocked", "Original scan preserved"], strategies: [
    { label: "Ask a reviewer to confirm the amount", review: "Compare the original scan with the arithmetic and explicitly confirm the uncertain digit.", plan: ["Reviewer inspects original", "Fixture reviewer confirms 3,100", "Approve filename using verified amount"], result: ["Verified amount: 3,100", "Rename based on reviewed field", "Original scan retained"], tradeoff: "Produces a useful structured result but adds human review time. Arithmetic is supporting evidence, not a substitute for the original." },
    { label: "File under a neutral identifier for later review", review: "Avoid putting an uncertain amount into a filename or downstream payment data.", plan: ["Use scan-023.pdf", "Mark amount unverified", "Queue manual review"], result: ["Document filed without a guessed amount", "Amount remains pending", "No payment action performed"], tradeoff: "Keeps ingestion moving but leaves metadata incomplete and requires a visible review queue." }
  ], lesson: "Treat extracted fields as claims requiring validation. A confidence score does not itself establish correctness, and uncertain values should not silently drive actions." }),
  investigation({ id: 24, title: "The Renaming Domino Effect", topic: "References · coordinated changes", brief: "Rename a document without silently breaking links from other project files.", clues: [
    { title: "Proposed rename", text: "guide.md → setup-guide.md in the same folder." },
    { title: "Known references", text: "README.md and index.md both link to guide.md." },
    { title: "Scan coverage", text: "The fixture scan covers this repository only; external bookmarks are unknown." }
  ], shortcut: "Rename the document and ignore inbound links", rejection: "The known references would point to a missing target. The plan is incomplete even if the rename itself succeeds.", rejectedEvidence: ["Two known broken references predicted", "Rename not applied"], strategies: [
    { label: "Rename and update the known references together", review: "Include dependent edits in the reviewed change set and check every known link afterward.", plan: ["Rename guide.md", "Update README.md and index.md", "Run link verification; report external uncertainty"], result: ["Known local links resolve", "Old external bookmarks may still fail", "Change set and coverage recorded"], tradeoff: "Leaves a cleaner local structure but cannot promise that unknown external references survive." },
    { label: "Keep the old location as a compatibility page", review: "Add the new page and retain a short old-path page directing readers to it. Avoid maintaining two conflicting full copies.", plan: ["Create setup-guide.md", "Replace guide.md with an intentional compatibility notice", "Verify local navigation"], result: ["Old path still opens a useful notice", "New guide available", "Compatibility artifact remains to maintain"], tradeoff: "Preserves a route for existing readers but adds a compatibility page and an eventual retirement decision." }
  ], lesson: "A file can be part of a reference graph. Review effects on its consumers, not just the local rename operation." }),
  investigation({ id: 25, title: "Two Agents, One File", topic: "Concurrency · ownership", brief: "Resolve competing agent plans before both try to move the same source.", clues: [
    { title: "Agent A", text: "Proposes Inbox/report.txt → Finance/report.txt." },
    { title: "Agent B", text: "Proposes the same source → Archive/report.txt." },
    { title: "Authority", text: "Neither proposal has execution approval; the source is still in Inbox." }
  ], shortcut: "Run both plans and let the fastest agent decide", rejection: "A race does not resolve intent. One agent may act on stale state, and timing is not an authorization policy.", rejectedEvidence: ["Conflicting plans detected", "No move executed"], strategies: [
    { label: "Ask the owner to choose the destination", review: "Present both proposals and approve only the owner’s selected destination.", plan: ["Owner selects Finance in this fixture", "Invalidate Archive proposal", "Recheck source and execute Finance plan"], result: ["File moved once to Finance", "Agent B notified that its proposal is invalid", "Owner decision recorded"], tradeoff: "Resolves business intent explicitly but requires a human decision." },
    { label: "Serialize planning under the declared routing rule", review: "The fixture’s approved routing rule says financial reports go to Finance. A coordinator applies it, invalidates both old plans, and issues one fresh plan for approval.", plan: ["Apply declared routing rule", "Create one fresh Finance proposal", "Obtain approval and revalidate before execution"], result: ["One coordinated move to Finance", "Old proposals rejected", "Rule and approval recorded"], tradeoff: "Reduces repeated human arbitration when a valid rule exists, but coordination must enforce exclusive execution—not merely issue advisory messages." }
  ], lesson: "Agent collaboration needs coordination and authority. Locks or queues serialize actions; they do not by themselves decide the right destination." }),
  investigation({ id: 26, title: "The Event That Arrived Twice", topic: "Idempotency · duplicate delivery", brief: "Process two notifications for one file version without producing two outputs.", clues: [
    { title: "Notifications", text: "Events E1 and E2 both refer to file F9, content version V3." },
    { title: "Existing operation", text: "Operation key F9:V3:classify already has a committed output record." },
    { title: "Scope", text: "The effect and deduplication record are in one simulated transactional store. No external side effect is involved." }
  ], shortcut: "Treat each notification as a new business operation", rejection: "Delivery identity differs from operation identity. Two events for the same effect must not automatically create two outputs.", rejectedEvidence: ["Duplicate business operation detected", "Second output not created"], strategies: [
    { label: "Return the recorded outcome for this operation key", review: "Use an atomic uniqueness rule around the operation record, not a check-then-write race.", plan: ["Look up F9:V3:classify", "Reuse committed outcome", "Acknowledge duplicate delivery"], result: ["One stored output", "Both deliveries accounted for", "No repeated effect"], tradeoff: "Efficient for already committed operations; key design must distinguish new versions and different operations." },
    { label: "Reconcile output and operation record first", review: "Verify the recorded result still exists and matches the expected file version before acknowledging the duplicate.", plan: ["Check output identity and version", "Confirm committed record agrees", "Reuse verified result"], result: ["Record and output reconciled", "One output retained", "Duplicate acknowledged"], tradeoff: "Adds verification work but catches inconsistent state. External effects would need their own idempotency or reconciliation strategy." }
  ], lesson: "Do not claim universal exactly-once execution from a local deduplication key. Identify the actual effect and its transactional boundary." }),
  investigation({ id: 27, title: "The Automation That Triggers Itself", topic: "Watchers · feedback loops", brief: "Stop an organizer from repeatedly processing its own generated summaries.", clues: [
    { title: "Watch scope", text: "The watcher monitors Demo recursively, including Demo/Generated." },
    { title: "Effect", text: "Processing a document writes a summary into Demo/Generated, creating another event." },
    { title: "Observed pattern", text: "summary.txt → summary-summary.txt → summary-summary-summary.txt." }
  ], shortcut: "Add a short delay between events and keep the same rules", rejection: "A delay slows the loop but does not remove the feedback path.", rejectedEvidence: ["Generated output still matches input scope", "Recurring work remains possible"], strategies: [
    { label: "Separate watched inputs from generated outputs", review: "Restrict the watcher to Demo/Inbox and write results to a non-watched output directory.", plan: ["Watch Demo/Inbox only", "Write to Demo/Generated", "Verify output events are outside input scope"], result: ["One input produces one summary in the fixture", "Summary event not consumed", "Feedback path removed"], tradeoff: "Clear structural separation, but requires users and producers to respect the input/output layout." },
    { label: "Filter trusted origin records and deduplicate work", review: "Keep the wider scope but reject events tied to the system’s own recorded operations. Do not trust an arbitrary user-supplied origin label.", plan: ["Record output origin in controlled operation store", "Ignore matching self-generated events", "Use operation keys for repeated notifications"], result: ["Self-generated events ignored", "Other permitted inputs still processed", "No recursive summary chain"], tradeoff: "Supports a flexible layout but has more policy and bookkeeping complexity than separating directories." }
  ], lesson: "Fix the feedback relationship, not just its speed. Folder watchers need explicit input boundaries and duplicate-event handling." }),
  investigation({ id: 28, title: "The Backup That Cannot Restore", topic: "Restore testing · integrity", brief: "Investigate a backup labelled successful that cannot restore a required document.", clues: [
    { title: "Backup banner", text: "The job reports success because its copy process exited normally." },
    { title: "Expected manifest", text: "Required files: brief.txt, budget.csv, delivery.txt." },
    { title: "Restore test", text: "A clean test restore contains brief.txt and budget.csv only. delivery.txt is missing." }
  ], shortcut: "Accept the success banner and delete the originals", rejection: "The restore test contradicts the banner. The backup has not met the recovery requirement.", rejectedEvidence: ["Missing required file: delivery.txt", "Originals retained", "Backup not certified recoverable"], strategies: [
    { label: "Repair the backup and repeat a full restore test", review: "Investigate the omission, add the missing file under a new verified manifest, and test recovery again without overwriting the source.", plan: ["Correct exclusion rule in fixture", "Rebuild backup manifest", "Restore into isolated test location and compare contents"], result: ["All three required files restored in test", "Manifest and content checks pass", "Originals remain intact"], tradeoff: "Repairs the intended backup but requires time and a repeatable restore test; success applies only to what was actually tested." },
    { label: "Create an independent verified recovery copy", review: "Keep the flawed backup flagged and produce a separate verified copy of the required files.", plan: ["Preserve originals and failed evidence", "Make independent recovery copy", "Test its restore against required manifest"], result: ["Independent restore test passes", "Old backup remains flagged incomplete", "Repair work still open"], tradeoff: "Restores a recovery option sooner but adds storage and does not fix the original backup process." }
  ], lesson: "A backup is useful when it can meet a tested recovery need. Exit codes, file counts, and successful uploads are not substitutes for a restore test." }),
  investigation({ id: 29, title: "The Approval That Expired", topic: "Scheduled work · authorization lifetime", brief: "Handle a queued move that starts after its approval window has closed.", clues: [
    { title: "Approval", text: "Plan P9 was approved at 09:00 with a 30-minute validity window." },
    { title: "Execution time", text: "The delayed worker starts at 11:00." },
    { title: "Current state", text: "The destination now contains a different file with the planned name." }
  ], shortcut: "Run the original plan because someone approved it earlier", rejection: "The approval has expired and the destination has changed. Neither condition can be ignored by the worker.", rejectedEvidence: ["Approval expired at 09:30", "Destination collision detected", "No move executed"], strategies: [
    { label: "Cancel the queued job and notify its owner", review: "End this job explicitly without deleting the source. A future request must start with a new plan.", plan: ["Mark job cancelled, not successful", "Preserve source and destination", "Notify owner of expiry and conflict"], result: ["No changes", "Job no longer queued", "Owner has actionable reason"], tradeoff: "Simple and safe, but requires the user to initiate a fresh attempt." },
    { label: "Generate a revised plan for fresh approval", review: "Choose a conflict-free destination and obtain a new time-limited approval before acting.", plan: ["Propose a new destination name", "Request fresh approval", "Recheck conditions immediately before execution"], result: ["Fixture owner approves revised plan", "Fresh checks pass", "Move recorded under new approval"], tradeoff: "Can complete the task after review, but the old approval is never silently extended or reused." }
  ], lesson: "Approval has scope, content, and sometimes a lifetime. Delayed execution must revalidate all of them rather than relying on a historical yes." }),
  investigation({ id: 30, title: "Investigate the Missing File", topic: "Read-only investigation · evidence trails", brief: "Explain where a document went without making the incident harder to investigate.", clues: [
    { title: "User report", text: "The user cannot find Inbox/proposal.txt and thinks it was deleted." },
    { title: "Operation record", text: "Job J42 recorded a move to Quarantine/proposal.txt after a duplicate review." },
    { title: "Observed state", text: "The quarantine file exists and matches the original recorded content fingerprint. The old path is empty." }
  ], shortcut: "Run another organizer scan to see if it fixes the problem", rejection: "Another mutation would add noise and might move the evidence again. Establish the current facts first.", rejectedEvidence: ["Organizer run withheld", "Current file and operation record preserved"], strategies: [
    { label: "Report the location and request restoration approval", review: "Explain the evidence, then ask whether the owner wants the file restored. Do not restore merely because it was reported missing.", plan: ["Report J42 and quarantine path", "Explain fingerprint match and limits", "Request a separate restoration decision"], result: ["User learns the file was moved, not proven deleted", "Restoration approval pending", "No further changes"], tradeoff: "Resolves the mystery and prepares recovery while preserving a separate authorization step." },
    { label: "Produce a read-only incident summary", review: "Record timeline, observations, and uncertainties for the owner without proposing another operation yet.", plan: ["Record report, J42, and current location", "Separate observations from assumptions", "Preserve evidence and leave file in place"], result: ["Incident summary ready", "Quarantine file unchanged", "No claim about unobserved earlier events"], tradeoff: "Best when explanation is the immediate goal; the user must separately decide whether any recovery action is needed." }
  ], lesson: "Diagnosis is not authorization to repair. Establish what happened using current observations and records, and label any remaining uncertainty." })
];
