import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const base=path.join(root,'docs/training');
const courses=JSON.parse(await fs.readFile(path.join(base,'series.json'),'utf8'));
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function wrap(s,width){const lines=[''];for(const w of s.split(' ')){const i=lines.length-1;if(lines[i] && (lines[i]+' '+w).length>width)lines.push(w);else lines[i]+=(lines[i]?' ':'')+w;}return lines;}
function label(s,x,y,width,size,bold=false){return wrap(s,width).map((line,i)=>`<text x="${x}" y="${y+i*(size+9)}" font-size="${size}"${bold?' font-weight="700"':''}>${escape(line)}</text>`).join('');}
for(const c of courses){
  const cards=c.steps.map(([title,body],i)=>{const x=i%2?630:50,y=i<2?155:415;return `<rect x="${x}" y="${y}" width="520" height="195" rx="18" fill="white" stroke="#b8cfed" stroke-width="2"/>`+label(`${i+1} · ${title}`,x+25,y+42,31,25,true)+label(body,x+25,y+113,39,23);}).join('');
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="790" viewBox="0 0 1200 790" role="img" aria-label="${escape(c.title)} flow"><rect width="1200" height="790" rx="24" fill="#edf4ff"/><g font-family="Segoe UI,Arial,sans-serif" fill="#173964">${label(c.title,50,60,61,32,true)}${cards}<rect x="50" y="660" width="1100" height="95" rx="15" fill="#dae8ff"/>${label(c.limit,75,696,81,23)}</g><g fill="none" stroke="#245ac4" stroke-width="3"><path d="M575 250h40m-12 -9l12 9 -12 9M890 355v25H310v25m-9 -12l9 12 9 -12M575 510h40m-12 -9l12 9 -12 9"/></g></svg>`;
  await fs.mkdir(path.join(base,c.slug,'assets'),{recursive:true});
  await fs.writeFile(path.join(base,c.slug,'assets/flow.svg'),svg);
}
const lines=['# Your Practical Software Engineering Workshops','','## At a glance','','Start with one workshop, perform its exercise, and keep a short evidence record before moving on. These are separate reading documents, not one enormous course. Each has a blue HTML edition, a Markdown source, and local practice material. Nothing is deployed automatically.','','## The learning order','','| Order | Workshop | What you will practice |','|---|---|---|','| 1 | [CI/CD](ci-cd/CI-CD-FROM-SOLO-TO-TEAM.md) | PR checks, staging, approval and release rejection |','| 2 | [Debugging](debugging/DEBUGGING-WITHOUT-GUESSING.md) | Reproduce, trace, inspect, fix and verify |','| 3 | [Testing](testing/TESTING-THAT-CATCHES-REAL-PROBLEMS.md) | Meaningful assertions and forbidden side effects |'];
for(const [i,c] of courses.entries())lines.push(`| ${i+4} | [${c.title}](${c.slug}/${c.file}) | ${c.purpose} |`);
lines.push('','## How to use each workshop','','Read the scenario first. Run the smallest exercise. Predict the result before changing code. Record the observed result and explain any difference. Finish the independent challenge without immediately asking AI for the finished solution.','', 'The JavaScript labs use Node; the newer Python labs use the standard library. Git practice also needs Git. The Docker workshop requires Docker, which was not available during authoring. The accessibility workshop contains a browser-only simulator. No exercise needs real patient data, real credentials, or access to your personal files.','','## Understand the verification boundary','','The runnable examples are deliberately small. Passing their checks is evidence about those examples, not production certification. Some exercises demonstrate expected failures or leave a final challenge unsolved. Docker image build/run and real independent PR approvals require your own environment and participation.','', '| Workshop | Important limitation |','|---|---|');
for(const c of courses)lines.push(`| ${c.title} | ${c.limit} |`);
lines.push('','## Your evidence notebook','','For every workshop record: requirement, exact command or interaction, expected result, actual result, explanation, and remaining uncertainty. A useful portfolio demonstration includes this reasoning as well as screenshots or green test output.','','## Where the materials live','','Each workshop is a direct subfolder of `docs/training`. Its `exercises` folder contains practice code; its `assets` folder contains original diagrams. HTML files are standalone reading editions with embedded styles and diagrams. The website publishes only the Markdown entries explicitly listed in the library publication manifest. Practice code is not automatically exposed as a website download.','','The master document directory also lists these workshops. Use the source repository to copy exercise folders; the reading pages explain how to run them locally.','');
await fs.writeFile(path.join(base,'START-HERE.md'),lines.join('\n'));
console.log(`Generated ${courses.length} topic-specific diagrams and the 15-workshop index.`);
