const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const Module = require('node:module');
const path = require('node:path');
const filename = path.resolve(__dirname, '../lib/filepilot-lab.ts');
const compiled = ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } });
const loaded = new Module(filename, module);
loaded._compile(compiled.outputText, filename);
const { seedFiles, makePlan, planErrors, applyPlan } = loaded.exports;
const original = structuredClone(seedFiles);
const plan = makePlan(seedFiles);
assert.equal(plan.length, 4);
assert.throws(() => applyPlan(seedFiles, plan, false), /approve/);
const result = applyPlan(seedFiles, plan, true);
assert.equal(result.length, seedFiles.length);
assert.deepEqual(result.map(f => f.content), seedFiles.map(f => f.content));
assert.deepEqual(seedFiles, original);
assert.equal(result.find(f => f.id === '5').path, 'Inbox/archive.zip');
assert.throws(() => applyPlan(result, plan, true), /Source changed/);
const conflict = [...seedFiles, { id: 'existing', path: 'Documents/meeting.txt', content: 'Keep me' }];
assert.throws(() => applyPlan(conflict, plan, true), /overwrite/);
const revised = plan.map(m => m.id === '4' ? {...m, to:'Documents/meeting-from-inbox.txt'} : m);
assert.equal(applyPlan(conflict, revised, true).find(f => f.id === 'existing').content, 'Keep me');
assert.ok(planErrors(seedFiles, [{...plan[0], to:'../outside.txt'}]).length);
assert.ok(planErrors(seedFiles, [plan[0], plan[0]]).length);
assert.ok(planErrors(seedFiles, []).length);
console.log('PASS: planning, approval, collision, revised plan, stale source, path boundary, duplicate moves, content preservation, and immutable snapshot.');
